//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgaNice.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrgaNice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El capítulo está siendo utilizado por otro proceso..
        /// </summary>
        public static string error_chapter_busy {
            get {
                return ResourceManager.GetString("error_chapter_busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra el directorio..
        /// </summary>
        public static string error_directory_not_found {
            get {
                return ResourceManager.GetString("error_directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un capítulo con ese nombre..
        /// </summary>
        public static string error_existent_chapter {
            get {
                return ResourceManager.GetString("error_existent_chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una unidad con ese nombre..
        /// </summary>
        public static string error_existent_unit {
            get {
                return ResourceManager.GetString("error_existent_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la unidad no es soportado por tu sistema..
        /// </summary>
        public static string error_not_supported_name {
            get {
                return ResourceManager.GetString("error_not_supported_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permisos de escritura..
        /// </summary>
        public static string error_not_write_permissions {
            get {
                return ResourceManager.GetString("error_not_write_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al crear la unidad..
        /// </summary>
        public static string error_unespected {
            get {
                return ResourceManager.GetString("error_unespected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un capítulo con ese nombre..
        /// </summary>
        public static string error_unexistent_chapter {
            get {
                return ResourceManager.GetString("error_unexistent_chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una unidad con ese nombre..
        /// </summary>
        public static string error_unexistent_unit {
            get {
                return ResourceManager.GetString("error_unexistent_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado al borrar el  capítulo..
        /// </summary>
        public static string error_unexpected_chapter_delete {
            get {
                return ResourceManager.GetString("error_unexpected_chapter_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La unidad que intenta eliminar no está vacía..
        /// </summary>
        public static string error_unit_not_empty {
            get {
                return ResourceManager.GetString("error_unit_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} se ha creado en {1}!.
        /// </summary>
        public static string success_chapter_created {
            get {
                return ResourceManager.GetString("success_chapter_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El capítulo {0} se borró de {1}!.
        /// </summary>
        public static string success_chapter_deleted {
            get {
                return ResourceManager.GetString("success_chapter_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La unidad {0} se creó correctamente!.
        /// </summary>
        public static string success_unit_created {
            get {
                return ResourceManager.GetString("success_unit_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La unidad {0} se borró correctamente!.
        /// </summary>
        public static string success_unit_deleted {
            get {
                return ResourceManager.GetString("success_unit_deleted", resourceCulture);
            }
        }
    }
}
